name: Crawl news

#Run automatically every 24 hours
on:
  schedule:
    - cron: "0 0 * * *"

  # This command allows to run the Action automatically from the Actions tab.
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.18' 
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - run: pip install lxml
      - run: python main.py
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update NEWS.md"
          git push
